# Generated by Django 3.2.16 on 2023-04-12 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20230412_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='update',
            field=models.DateTimeField(auto_now=True, verbose_name='Время изменения'),
        ),
    ]
